spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/travel-companion-search
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:liquibase/db.changelog.yaml
    enabled: true
  security:
    jwt:
      secret: Zmpkc25mbXNkamZzbmRqd3JlZWUzMjRtZG1mZG1rbGZtc2YyM3JmZHM=
      access: 2592000000
      refresh: 2592000000
  mail:
    host: smtp.gmail.com
    port: 587
    username: romatempforjet@gmail.com
    password: ydkl aobk ctcc jloj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
minio:
  bucket: images
  url: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
user:
  avatarName: d8b5d0a738295345ebd8934b859fa1fca1c8c6ad.jpeg

